# Generated by Django 4.2 on 2025-06-11 07:06

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model('tracker', 'Category')
    categories = [
        'Bills',
        'Food',
        'Clothes',
        'Medical',
        'Housing',
        'Salary',
        'Social',
        'Transport',
        'Vacation'
    ]
    for name in categories:
        Category.objects.get_or_create(name=name)

class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0003_alter_transaction_options_categorybudget"),
    ]

    operations = [
        migrations.RunPython(create_categories),
    ]
